export const GAME_CONFIG = {
  COURT_WIDTH: 800,
  COURT_HEIGHT: 600,
  
  BALL_RADIUS: 8,
  BALL_SPEED: 300,
  
  PADDLE_WIDTH: 10,
  PADDLE_HEIGHT: 80,
  PADDLE_SPEED: 400,
  PADDLE_OFFSET: 20,
  
  MAX_SCORE: 5,
  TICK_RATE: 60,
  
  WS_UPDATE_RATE: 60,
} as const;

export const DT = 1 / GAME_CONFIG.TICK_RATE;